### ISSUE TITLE
Invisible mouse cursor on spectator hud and commandmenu

### ISSUE THREAD

**Issue by gundogfan** [LevShisterov/BugfixedHL#28]
> ] version
> Protocol version 48
> Exe version 1.1.2.1 (valve)
> Exe build: 16:05:41 Jun 15 2009 (4554)
> 

> ] about
> Bugfixed and improved Half-Life client
> Version: 1.5.0+master.e293fe0
> Build options: VGUI2 support    game build 4554    auto-updater    
> Github: https://github.com/tmp64/BugfixedHL
> Discussion forum: http://aghl.ru/forum/viewtopic.php?f=36&t=686

**Comment by ddagger1** [comment]
Thanks tmp64 for fixing this
