### ISSUE TITLE
AG teamchat locations

### ISSUE THREAD

**Issue by noctuum** [LevShisterov/BugfixedHL#4]
пожалуйста допили локации для тимчата в АГ

**Comment by LevShisterov** [comment]
Ok. Some later, at vacation now.

**Comment by noctuum** [comment]
обещанного три года ждут, да? :suspect: :clock4:

:)

**Comment by LevShisterov** [comment]
What is the size of the largest (in bytes and lines) .loc file that you do have?

**Comment by noctuum** [comment]
3 098 bytes, 1 line, each loc and x,y,z coords of the loc file are separated with `#`
if put each loc in the file on a separate line there will be 67 lines

**Comment by LevShisterov** [comment]
Resolved in 6324464e7ddf394da5eca51735d4c47597956902.
