### ISSUE TITLE
'agrecord' issue

### ISSUE THREAD

**Issue by noctuum** [LevShisterov/BugfixedHL#6]
Please make `agrecord` command working for non-english steam interface
For AGmod

**Comment by LevShisterov** [comment]
Didn't got the problem.

**Comment by noctuum** [comment]
`agrecord` should start a demo recording with predefined name
(like this: `\results\%YYYY%-%MM%\%map%-%timestamp%.dem`)

if steam has russian language interface, it tries to record .dem file in `\ag_russian\results` and unfortunately fails.

but it works if steam has english language interface, then .dem file is recording into `\ag\results` folder successfully

**Comment by LevShisterov** [comment]
Fixed in 44b8dcf9.
